services:
  donetick:
    image: donetick/donetick:v0.1.43
    container_name: donetick
    user: "1011:1011"
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      - /opt/donetick/data/donetick-data:/donetick-data
      - /opt/donetick/data/config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db

    networks:
        - proxy_net
        - donetick_net

networks:
  donetick_net:
    name: donetick_net
    external: true
  proxy_net:
    name: proxy_net
    external: true