services:
  gitea:
    image: docker.io/gitea/gitea:1.25.1
    container_name: gitea
    environment:
      - USER_UID=1005
      - USER_GID=1005
    restart: unless-stopped
    networks:
      - proxy_net
    volumes:
      - /opt/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
#      - "222:22"

networks:
  proxy_net:
    name: proxy_net
    external: true
